library(RColorBrewer)
library(plyr)
library(plotrix)
library(extrafont)
library(fontcm)
loadfonts()

rm(list=ls())
source('paths.R')
source('R/functions-analyses.R')
source('R/functions-figures.R')
load('output/RDatafiles/bitesData.RData')
load('output/RDatafiles/coverData.RData')
load('output/RDatafiles/dietData.RData')
load('output/RDatafiles/selectivityAnalysis.RData')
load('output/RDatafiles/bitesAnalysis.RData')
load('output/RDatafiles/rnaDnaAnalysis.RData')
load('output/RDatafiles/densityAnalysis.RData')

to.pdf(fig1(), fig.path('fig1.pdf'), width=9, height=5)
embed_fonts(fig.path('fig1.pdf'))
to.pdf(fig2(), fig.path('fig2.pdf'), width=9, height=4)
embed_fonts(fig.path('fig2.pdf'))
to.pdf(fig3(), fig.path('fig3.pdf'), width=4.5, height=9)
embed_fonts(fig.path('fig3.pdf'))
to.pdf(fig4(), fig.path('fig4.pdf'), width=5, height=5)
embed_fonts(fig.path('fig4.pdf'))
to.pdf(fig5(), fig.path('fig5.pdf'), width=5, height=5)
embed_fonts(fig.path('fig5.pdf'))
to.pdf(figS1(), fig.path('figS1.pdf'), width=4.5, height=9)
embed_fonts(fig.path('figS1.pdf'))
